# Generated by Django 3.1 on 2023-10-10 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dosen", "0002_auto_20231010_0903"),
        ("mahasiswa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionAwnser",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="uploads/")),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="dosen.question")),
            ],
        ),
    ]
