# Generated by Django 3.1 on 2023-10-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_admin", "0002_alter_account_username"),
    ]

    operations = []
