# Generated by Django 3.1 on 2023-10-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dosen", "0001_initial"),
    ]

    operations = []
